const app=document.getElementById('app');
const VERSION='0.7';
const state={playerName:localStorage.getItem('mongyeong.playerName')||'여행자',level:Number(localStorage.getItem('mongyeong.level')||1),chapter:1};
let scenes=window.CHAPTER_1||[];let index=-1;let locked=false;
function save(){localStorage.setItem('mongyeong.playerName',state.playerName);localStorage.setItem('mongyeong.level',String(state.level));}
function mount(html,onReady){const old=app.firstElementChild;if(old){old.classList.add('leaving');setTimeout(()=>{app.innerHTML=html;onReady?.()},420)}else{app.innerHTML=html;onReady?.()}}
function title(){mount(`<main class="screen title"><div class="logo">夢境</div><div class="subtitle">잠든 세계</div><div class="start">화면을 터치하여 시작</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.addEventListener('click',next,{once:true}))}
function renderName(){mount(`<main class="screen black"><div class="name-wrap"><div class="text">내 이름은—</div><input id="name" class="name-input" maxlength="10" placeholder="이름을 입력하세요" value="${state.playerName==='여행자'?'':state.playerName}"><button id="confirm" class="confirm">확인</button></div><div class="version">Ver. ${VERSION}</div></main>`,()=>{const input=document.getElementById('name');input.focus();const go=()=>{const value=input.value.trim();if(!value)return;state.playerName=value;save();next()};document.getElementById('confirm').onclick=go;input.addEventListener('keydown',event=>{if(event.key==='Enter')go()})})}
function levelTheme(level){if(level<=25)return'level-blue';if(level<=50)return'level-noise';if(level<=75)return'level-red-noise';return'level-fracture'}
function renderLevelUp(scene){state.level=scene.to;save();mount(`<main class="screen status ${levelTheme(scene.to)}"><section class="box"><div class="chapter-title">LEVEL UP</div><div class="text" style="margin-top:18px">Lv. ${scene.from} → Lv. ${scene.to}</div></section><div class="hint">터치하여 계속</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.onclick=next)}
function renderScene(scene){if(scene.opening){mount(`<main class="screen chapter"><section class="box"><div class="chapter-title">CHAPTER ${state.chapter}</div></section><div class="hint">터치하여 계속</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.onclick=next);return}if(scene.clear){mount(`<main class="screen chapter"><section class="box"><div class="chapter-title">CHAPTER ${state.chapter} CLEAR</div></section><div class="hint">터치하여 계속</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.onclick=next);return}if(scene.type==='reward'){mount(`<main class="screen chapter"><section class="box"><div class="chapter-sub">CHAPTER CLEAR REWARD</div><div class="text" style="margin-top:18px">경험치 획득<br>EXP +${scene.exp}</div><div class="exp"><span></span></div></section><div class="hint">터치하여 계속</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.onclick=next);return}if(scene.type==='levelup'){renderLevelUp(scene);return}const speaker=typeof scene.speaker==='function'?scene.speaker(state):scene.speaker;const body=typeof scene.dynamic==='function'?scene.dynamic(state):scene.text;mount(`<main class="screen ${scene.type}"><section class="box">${speaker?`<div class="speaker">${speaker}</div>`:''}<div class="text">${body.replace(/\n/g,'<br>')}</div></section><div class="hint">터치하여 계속</div><div class="version">Ver. ${VERSION}</div></main>`,()=>app.firstElementChild.onclick=next)}
function next(){if(locked)return;locked=true;setTimeout(()=>locked=false,480);index++;if(index>=scenes.length){index=scenes.length-1;return}const scene=scenes[index];if(scene.type==='name')renderName();else renderScene(scene)}
title();