window.CHAPTER_1=[
{type:'chapter',opening:true},
{type:'black',text:'……여기는 어디지?'},{type:'black',text:'아니.\n그보다 먼저—'},{type:'black',text:'나는 누구지?'},{type:'name'},
{type:'black',dynamic:s=>`그래.\n내 이름은 ${s.playerName}.`},{type:'black',text:'그것만은 기억난다.\n그런데 왜 여기 있는지는…… 모르겠다.'},
{type:'forest',text:'눈을 뜨자 가장 먼저 빛이 보였다.\n푸른빛이 높은 나뭇잎 사이를 비집고 내려와 숲바닥에 조각조각 흩어져 있었다.'},
{type:'forest',text:'천천히 몸을 일으켰다.\n축축한 흙냄새. 서늘한 바람. 이름 모를 꽃들이 발목 높이에서 흔들렸다.'},
{type:'forest',text:'나무는 하늘을 가릴 만큼 높았다.\n잎 끝에는 작은 빛들이 맺혀 있었고, 바람이 불 때마다 허공으로 흩어졌다.'},
{type:'forest',text:'아름답다.\n그런데 너무 조용했다.'},{type:'forest',text:'새소리도 없고, 벌레 우는 소리도 없다.\n내 발이 풀잎을 밟는 소리만 따라왔다.'},
{type:'forest',text:'가만히 있을 수는 없었다.\n일단 이 숲을 벗어나기로 했다.'},{type:'forest',text:'얼마나 걸었을까.\n앞쪽 덤불에서 바스락거리는 소리가 났다.'},
{type:'danger',text:'걸음을 멈췄다.\n검은 무언가가 나무 뒤에서 천천히 몸을 드러냈다.'},{type:'danger',text:'짐승처럼 네 발로 서 있었지만, 짐승이라고 하기엔 이상했다.\n몸의 윤곽은 연기처럼 계속 흔들리고 있었다.'},
{type:'danger',text:'급히 주변을 둘러봤다.\n돌멩이 몇 개와 젖은 나뭇가지뿐. 손에 쥘 만한 건 아무것도 없었다.'},{type:'black',text:'……도망쳐야 한다.'},
{type:'danger',text:'뒤돌아 달렸다.\n나뭇가지가 얼굴을 스쳤고, 바로 뒤에서 거친 숨소리가 따라붙었다.'},{type:'danger',text:'점점 가까워진다.\n뒤를 돌아볼 여유도 없었다.'},
{type:'forest',text:'그 순간, 누군가 내 손목을 거칠게 잡아당겼다.'},{type:'forest',text:'몸이 옆으로 휘청였다.\n검은 발톱이 방금까지 내가 있던 자리를 찢고 지나갔다.'},
{type:'forest',speaker:'???',text:'가만히 계세요.'},{type:'forest',text:'처음 보는 소녀였다.\n나를 등 뒤로 밀어낸 그녀가 한 손을 들어 올렸다.'},
{type:'forest',text:'푸른빛이 손끝에 모이더니 활의 형태를 만들었다.\n시위를 당기자 빛으로 된 화살이 조용히 나타났다.'},
{type:'battle'},
{type:'danger',text:'빛의 화살에 밀려난 검은 생명체가 크게 휘청였다.\n하지만 쓰러지지는 않았다.'},
{type:'danger',text:'놈이 마지막 힘을 짜내듯 몸을 낮췄다.\n그리고 곧장 소녀를 향해 달려들었다.'},
{type:'black',text:'위험해.'},{type:'danger',text:'생각할 틈도 없이 달려들었다.\n주먹을 꽉 쥐고, 놈의 옆구리를 있는 힘껏 내질렀다.'},
{type:'danger',text:'주먹이 닿은 순간—\n검은 몸이 안쪽부터 갈라지며 무너져 내렸다.'},{type:'danger',text:'검은 생명체는 몇 걸음 비틀거리더니 그대로 바닥에 쓰러졌다.\n움직임이 멎었다.'},
{type:'forest',text:'순간, 숲이 조용해졌다.\n나는 천천히 주먹을 내려다봤다.'},{type:'forest',text:'소녀도 쓰러진 생명체와 나를 번갈아 바라보고 있었다.\n아무 말도 하지 못한 채.'},
{type:'levelup',from:1,to:2},
{type:'forest',speaker:'???',text:'……방금, 뭘 하신 거예요?'},{type:'forest',speaker:s=>s.playerName,text:'저도…… 모르겠습니다.'},
{type:'forest',speaker:'???',text:'맨손으로 잡으셨잖아요.'},{type:'forest',speaker:s=>s.playerName,text:'그냥 달려들길래…… 저도 모르게.'},
{type:'forest',text:'검은 안개가 흩어진 자리에 작은 결정 하나가 떨어졌다.\n검붉은빛이 결정 안쪽에서 희미하게 일렁였다.'},
{type:'forest',speaker:'???',text:'악몽의 정수네요.'},{type:'forest',speaker:s=>s.playerName,text:'악몽……이요?'},
{type:'forest',speaker:'???',text:'아까 그 괴물 말이에요.\n그런데 정말 아무것도 모르세요?'},{type:'forest',speaker:s=>s.playerName,text:'네. 이름 말고는 기억나는 게 없습니다.'},
{type:'forest',speaker:'???',text:'……그렇군요.'},{type:'forest',speaker:'하루',text:'저는 하루예요.\n임무를 마치고 돌아가던 중이었어요.'},
{type:'forest',speaker:'하루',text:'일단 같이 가요.\n이 숲에 혼자 계시는 건 위험해요.'},{type:'forest',speaker:s=>s.playerName,text:'도와주셔서 감사합니다.\n부탁드리겠습니다.'},
{type:'black',text:'그렇게 나는 하루를 따라 숲을 나섰다.'},{type:'forest',text:'얼마쯤 걸었을까.\n빽빽하던 나무 사이로 조금씩 하늘이 보이기 시작했다.'},
{type:'forest',text:'숲의 끝을 지나자 바람의 냄새가 달라졌다.\n그리고 멀리, 거대한 도시의 외벽이 모습을 드러냈다.'},
{type:'city',text:'높은 외벽 너머로 수많은 건물과 불빛이 보였다.\n도시 바깥쪽에서는 무기를 든 헌터들이 외곽을 순찰하고 있었다.'},
{type:'gate',text:'입구에 가까워지자 경계 중이던 두 헌터가 우리 쪽을 돌아봤다.\n그중 한 명이 하루를 알아보고 먼저 손을 들었다.'},
{type:'gate',speaker:'헌터 1',text:'하루 씨. 오늘은 좀 늦으셨네요.'},{type:'gate',speaker:'하루',text:'네. 돌아오는 길에 일이 좀 있었어요.'},
{type:'gate',speaker:'헌터 2',text:'옆에 계신 분 때문에요?'},{type:'gate',speaker:'하루',text:'네. 자세한 건 들어가서 얘기할게요.'},
{type:'gate',speaker:'헌터 1',text:'알겠습니다. 고생하셨어요.'},{type:'gate',speaker:'하루',text:'두 분도 수고하세요.'},
{type:'city',text:'하루와 함께 입구를 지나 도시 안으로 들어섰다.\n숲과는 전혀 다른 소리와 빛이 한꺼번에 밀려왔다.'},
{type:'chapter',clear:true},{type:'reward',exp:100},{type:'levelup',from:2,to:3},
{type:'city',speaker:'하루',text:'중앙도시예요.\n여기까지 오셨으면 이제 괜찮을 거예요.'},
{type:'chapter2'},
{type:'mainLobby',speaker:'하루',text:'우선 길드로 가보자.\n네가 이곳 사람이라면 뭔가 기록이 남아 있을지도 몰라.\n나도 임무 완료 보고를 해야 하니까, 어차피 가야 하거든.'},
{type:'city',text:'길드 타일을 선택하자 화면이 천천히 어두워졌다.\n잠시 후, 밝은 햇빛과 함께 도시의 풍경이 시야를 가득 채웠다.'},
{type:'city',text:'넓은 거리를 따라 사람들이 끊임없이 오갔다.\n높고 낮은 건물들이 길 양옆으로 빼곡하게 이어져 있었다.'},
{type:'city',text:'가게 앞에서 물건을 고르는 사람. 길가에 앉아 이야기를 나누는 사람.\n무언가를 먹으며 웃고 떠드는 사람들까지.\n처음 보는 도시였지만 이상하리만큼 평범한 풍경이었다.'},
{type:'city',text:'하지만 조금만 자세히 바라보자 한 가지 이상한 점이 눈에 들어왔다.\n무기를 든 사람이 많았다.'},
{type:'city',text:'허리에 검을 찬 남자. 등에 거대한 창을 멘 여자.\n처음 보는 형태의 무기를 손질하며 길가에 앉아 있는 사람들까지.'},
{type:'city',text:'그리고 그들 대부분은 혼자가 아니었다.\n두 명, 세 명, 때로는 네 명씩 무리를 지어 같은 방향으로 향하고 있었다.'},
{type:'city',speaker:s=>s.playerName,text:'저 사람들은……?'},{type:'city',speaker:'하루',text:'아, 임무 나가는 사람들이야.'},{type:'city',speaker:s=>s.playerName,text:'임무?'},
{type:'city',text:'하루가 잠시 나를 바라봤다.\n그제야 다시 실감했다. 나는 정말 아무것도 모른다.\n내 이름을 제외하면.'},
{type:'city',text:'내가 누구인지. 어디서 왔는지.\n심지어 이곳이 어떤 세계인지조차.'},
{type:'city',speaker:'하루',text:'일단 길드부터 가자.\n네 기록이 남아 있다면 거기서 찾을 수 있을 거야.'},
{type:'city',text:'도시의 중심으로 가까워질수록 사람들의 수가 많아졌다.\n거대한 무기를 짊어진 이들. 온몸에 상처를 입은 채 동료의 부축을 받으며 돌아오는 이들.'},
{type:'city',text:'서로 웃으며 이야기하는 사람들 사이로, 누군가의 이름이 적힌 작은 꽃다발을 들고 조용히 걷는 사람도 보였다.'},
{type:'city',text:'나는 그 모습을 잠시 바라봤다.\n하루는 아무 말도 하지 않았다.'},
{type:'city',text:'얼마 지나지 않아 우리는 거대한 건물 앞에 도착했다.\n수많은 사람이 끊임없이 드나드는 곳.\n건물 정면에는 단 하나의 글자가 크게 새겨져 있었다.\n\nGUILD'},
{type:'city',speaker:'하루',text:'여기가 길드야.'},
{type:'guild',text:'문이 열렸다.\n순간, 도시의 소음과는 전혀 다른 활기가 밀려왔다.'},
{type:'guild',text:'넓은 홀. 벽을 가득 채운 수많은 임무 게시판.\n접수대 앞에 줄을 선 사람들.'},
{type:'guild',text:'테이블 위에 지도를 펼쳐놓고 작전을 논의하는 파티.\n새로운 동료를 찾으며 서로의 장비와 등급을 확인하는 사람들.'},
{type:'guild',text:'임무를 마치고 돌아온 이들은 접수대에 증표와 보고서를 제출하고 있었다.'},
{type:'guild',text:'이 건물은 단순히 사람들이 모이는 장소가 아니었다.\n이 도시의 모든 것이 이곳을 중심으로 움직이고 있었다.'},
{type:'guild',speaker:'하루',text:'뭐 해?\n이쪽이야.'},
{type:'guild',text:'나는 다시 하루를 따라 걸었다.\n내가 누구인지 알고 싶다면— 아마 이곳에서부터 시작해야 한다.'},
{type:'guild',text:'하루를 따라 접수대로 향했다.\n여러 명의 직원이 쉴 새 없이 사람들을 응대하고 있었다.'},
{type:'guild',text:'임무서를 제출하는 사람. 새로운 의뢰를 확인하는 사람.\n동료의 이름을 대며 무언가를 묻는 사람까지.'},
{type:'guild',speaker:'안내원',text:'하루 님?'},{type:'guild',speaker:'하루',text:'아, 안녕하세요.'},{type:'guild',speaker:'안내원',text:'무사히 돌아오셨네요. 임무는요?'},{type:'guild',speaker:'하루',text:'끝났어요. 완료 보고하러 왔어요.'},
{type:'guild',text:'하루는 품에서 작은 패를 꺼내 건넸다.\n안내원이 그것을 접수대 위 장치에 올려놓자 희미한 빛이 퍼졌다.'},
{type:'system',text:'임무 완료 확인\n\n악몽 토벌 완료'},
{type:'guild',text:'악몽.\n분명 처음 듣는 말이어야 했다.\n그런데 그 단어를 보는 순간 머릿속 어딘가가 희미하게 흔들렸다.'},
{type:'guild',text:'잡힐 듯하면서도 잡히지 않는 감각.\n나는 무심코 미간을 찌푸렸다.'},
{type:'guild',speaker:'안내원',text:'그런데…… 이분은?'},
{type:'guild',speaker:'하루',text:'저도 잘 몰라요.\n임무에서 돌아오는 길에 만났어요.\n이름 말고는 아무것도 기억하지 못해요.'},
{type:'guild',speaker:'안내원',text:'기억상실인가요?'},{type:'guild',speaker:s=>s.playerName,text:'아마도요.'},{type:'guild',speaker:'안내원',text:'이름은 기억하시고요?'},
{type:'guild',dynamic:s=>`${s.playerName}.\n\n내가 이름을 말하자 안내원은 곧바로 앞에 놓인 장치를 조작하기 시작했다.`},
{type:'guild',speaker:'안내원',text:'잠시만 기다려주세요.'},{type:'guild',text:'화면 위로 수많은 정보가 빠르게 지나갔다.\n그리고 잠시 후, 안내원의 손이 멈췄다.'},
{type:'guild',speaker:'안내원',text:'……어라?'},{type:'guild',speaker:'하루',text:'왜요?'},{type:'system',text:'검색 결과 없음'},
{type:'guild',speaker:s=>s.playerName,text:'없는 건가요?'},{type:'guild',speaker:'안내원',text:'네. 적어도 길드 기록에는요.'},{type:'guild',speaker:'하루',text:'그럴 수도 있어요?'},
{type:'guild',speaker:'안내원',text:'이름을 바꿨거나 등록 정보에 오류가 생겼을 가능성은 있어요. 하지만……\n정말 아무것도 기억나지 않으세요?'},
{type:'guild',speaker:s=>s.playerName,text:'네.'},{type:'guild',speaker:'안내원',text:'그럼 지금 머물 곳은 있으세요?'},{type:'guild',speaker:'안내원',text:'돈은요?'},{type:'guild',speaker:'안내원',text:'소지품이나 신분을 증명할 만한 것은요?'},
{type:'guild',text:'나는 천천히 고개를 저었다.\n안내원은 난처한 표정으로 하루를 바라봤다. 하루도 나를 바라봤다.'},
{type:'black',text:'나는 기억만 없는 게 아니었다.\n\n집도 없다.\n돈도 없다.\n신분도 없다.\n\n말 그대로—\n\n아무것도 없었다.'}
];