(()=>{
  window.CHAPTER_5=[
    {type:'black',text:'CHAPTER 5\n\n혼자 걷는 첫걸음'},
    {type:'lodging',text:'눈을 뜨자 이제는 제법 익숙해진 숙소의 천장이 보였다.\n어제 훈련의 피로가 아직 몸 곳곳에 남아 있었다.'},
    {type:'lodging',speaker:'주인공',text:'하루 씨는 오늘부터 다시 임무를 나간다고 했지.\n그렇다면 오늘은 혼자서 해봐야겠네.'},
    {type:'black',text:'혼자서도 계속해야 한다.\n우선 어제 배운 것부터 천천히 다시 해보자.'},
    {type:'lodging',text:'가볍게 몸을 풀고 준비를 마친 뒤 숙소를 나섰다.\n훈련장으로 향하는 길에는 따뜻한 아침 햇살이 조금씩 번지고 있었다.'},

    {type:'city',text:'헌터지구로 향하며 어제 배운 동작을 하나씩 떠올렸다.\n머릿속으로 순서를 되짚던 중, 길 건너편에서 익숙한 목소리가 들려왔다.'},
    {type:'city',speaker:'모모',text:'어, 좋은 아침.\n오늘도 훈련하러 가는 거야?'},
    {type:'relationshipChoice',screenType:'city',speaker:'주인공',text:'모모 씨에게 뭐라고 대답할까?',affinityKey:'momoAffinity',choices:[
      {text:'네. 어제 배운 걸 잊기 전에 조금 더 연습해보려고요.',playerLine:'네. 어제 배운 걸 잊기 전에 조금 더 연습해보려고요.',affinityKey:null,affinity:0,response:'그렇구나. 그래도 너무 무리하진 마.'},
      {text:'모모 씨도 같이 가실래요?',playerLine:'모모 씨도 같이 가실래요?',affinityKey:'momoAffinity',affinity:2,response:'같이 가고 싶긴 한데, 오늘은 따로 가볼 곳이 있어.\n다음에는 같이 가자.'},
      {text:'모모 씨는 어디 가세요?',playerLine:'모모 씨는 어디 가세요?',affinityKey:null,affinity:0,response:'나는…… 그, 놀이공원에 가려고.\n전에 지나가면서 봤는데 조금 궁금해서.'}
    ]},
    {type:'relationshipResponse',screenType:'city',speaker:'모모',fallback:'응. 잘 다녀와.'},
    {type:'city',speaker:'주인공',text:'알겠습니다.\n그럼 모모 씨도 잘 다녀오세요.'},
    {type:'city',speaker:'모모',text:'응. 훈련도 조심해서 하고 와.'},
    {type:'city',text:'모모와 인사를 나눈 뒤 다시 훈련장 쪽으로 걸음을 옮겼다.\n짧은 대화를 나누고 나니 혼자 향하던 길도 조금은 가볍게 느껴졌다.'},
    {type:'city',text:'얼마 지나지 않아 헌터지구의 높은 건물들이 시야에 들어왔다.\n그중 어제 방문했던 훈련 센터의 입구를 향해 곧장 걸어갔다.'},
    {type:'hunterDistrict'},

    {type:'trainingMap',unlocked:6},
    {type:'black',text:'기초 훈련 1-6\n\n혼자 시작하는 훈련'},
    {type:'city',text:'넓은 훈련장 안에는 주인공 혼자뿐이었다.\n어제 하루에게 배운 자세를 떠올리며 천천히 검을 꺼내 들었다.'},
    {type:'city',speaker:'주인공',text:'오늘은 정말 혼자네.\n하루 씨가 알려준 대로 천천히 해보자.'},
    {type:'city',speaker:'주인공',text:'처음부터 무리할 필요는 없어.\n하나씩 제대로 익히면 돼.'},
    {type:'soloTrainingBattle',stage:6,enemyType:'heavy'},
    {type:'city',speaker:'주인공',text:'어제보다는 검이 조금 가볍게 느껴져.\n계속하면 더 익숙해지겠지.'},

    {type:'trainingMap',unlocked:7},
    {type:'black',text:'기초 훈련 1-7\n\n훈련에 집중하다'},
    {type:'city',text:'시간이 흐를수록 훈련장 바닥에는 땀이 한 방울씩 떨어졌다.\n주인공은 같은 동작을 몇 번이고 반복했다.'},
    {type:'city',speaker:'주인공',text:'발을 먼저 움직이고...\n상대가 들어오는 순간에 검을 휘두른다.'},
    {type:'city',text:'검끝이 훈련체의 옆을 스쳐 지나갔다.\n주인공은 짧게 숨을 내쉬고 다시 자세를 잡았다.'},
    {type:'city',speaker:'주인공',text:'또 빗나갔어.\n한 번 더.'},
    {type:'soloTrainingBattle',stage:7,enemyType:'agile'},
    {type:'city',speaker:'주인공',text:'조금만 더 하면 잡힐 것 같아.\n여기서 멈추면 다시 처음부터일지도 몰라.'},

    {type:'trainingMap',unlocked:8},
    {type:'black',text:'한편, 길드장실'},
    {type:'city',text:'길드장실.\n길드장은 하루가 남긴 임무보고서를 천천히 읽고 있었다.'},
    {type:'city',text:'보고서의 한 대목에서 그의 손이 멈췄다.\n짧은 문장을 다시 한번 눈으로 훑었다.'},
    {type:'city',speaker:'길드장',text:'맨손으로 악몽을 쓰러뜨렸다...'},
    {type:'city',speaker:'부길드장',text:'무슨 문제라도 있습니까?'},
    {type:'city',speaker:'길드장',text:'처음 발견됐을 때는 무기도, 전투 경험도 없었다고 했지.'},
    {type:'city',speaker:'부길드장',text:'네. 하루의 보고도 그랬습니다.'},
    {type:'city',speaker:'길드장',text:'그런 사람이 맨손으로 악몽을 잡았다라...'},
    {type:'city',speaker:'부길드장',text:'하루가 도운 것 아닙니까?'},
    {type:'city',speaker:'길드장',text:'보고서에는 직접 쓰러뜨렸다고 적혀 있네.'},
    {type:'city',text:'잠시 침묵이 흘렀다.\n길드장은 보고서의 다음 장을 넘겼다.'},
    {type:'city',speaker:'길드장',text:'그리고 며칠 만에 무기 구현까지 성공했군.'},
    {type:'city',speaker:'부길드장',text:'성장이 빠르긴 합니다.'},
    {type:'city',speaker:'길드장',text:'빠르다는 말로 끝낼 수 있는 건지는 직접 봐야겠지.'},
    {type:'city',text:'길드장은 책상 위에 놓인 의뢰서 한 장으로 시선을 옮겼다.'},
    {type:'city',speaker:'길드장',text:'그 친구를 불러오게.'},
    {type:'city',speaker:'부길드장',text:'지금 길드 안에는 보이지 않습니다.\n아침에 훈련장으로 향했다는 말은 들었습니다.'},
    {type:'city',speaker:'길드장',text:'아직도 훈련장에 있는 건가.\n사람을 보내게. 돌아오는 대로 내게 바로 오라고 전하고.'},
    {type:'city',text:'같은 시각, 주인공은 길드에서 자신을 찾고 있다는 사실도 모른 채 훈련을 계속하고 있었다.'},
    {type:'city',speaker:'주인공',text:'조금만 더...\n이번에는 제대로 해보자.'},

    {type:'trainingMap',unlocked:9},
    {type:'black',text:'기초 훈련 1-9\n\n희미한 온기'},
    {type:'city',text:'훈련은 생각했던 것보다 훨씬 길어졌다.\n손끝은 떨리고 숨은 거칠어졌지만 주인공은 검을 내려놓지 않았다.'},
    {type:'soloTrainingBattle',stage:9,enemyType:'agile'},
    {type:'city',speaker:'주인공',text:'조금만...\n이것만 끝내면...'},
    {type:'city',text:'마지막으로 검을 들어 올리는 순간 시야가 크게 흔들렸다.\n손에서 검이 빠져나가고 몸도 그대로 앞으로 쓰러졌다.'},
    {type:'black',text:'얼마나 시간이 흘렀을까.\n\n차갑게 식어가던 몸을 따뜻한 기운이 천천히 감쌌다.'},
    {type:'black',speaker:'주인공',text:'따뜻해...'},
    {type:'black',text:'누군가 곁에 있는 것 같았다.\n하지만 눈을 뜰 수도, 목소리를 낼 수도 없었다.'},
    {type:'black',text:'부드러운 온기가 몸 깊숙이 스며들자 거칠었던 호흡이 조금씩 잦아들었다.\n아프고 무거웠던 몸도 믿기 어려울 만큼 편안해졌다.'},
    {type:'black',speaker:'주인공',text:'이상하다...\n아주 포근해.'},
    {type:'black',text:'희미한 의식 너머로 작은 발소리가 멀어졌다.\n주인공이 눈을 뜨기 전에 그 기척은 완전히 사라졌다.'},

    {type:'trainingMap',unlocked:10},
    {type:'black',text:'기초 훈련 1-10\n\n눈을 뜨다'},
    {type:'city',text:'주인공은 훈련장 벽에 기대어 천천히 눈을 떴다.\n흐릿했던 시야가 조금씩 제자리로 돌아왔다.'},
    {type:'city',speaker:'주인공',text:'내가... 쓰러졌던 건가?'},
    {type:'city',text:'분명 한계까지 몸을 몰아붙였지만 통증과 피로는 이상할 정도로 가라앉아 있었다.'},
    {type:'city',speaker:'주인공',text:'몸이 괜찮아졌어.\n아까 그 따뜻한 느낌은 뭐였지?'},
    {type:'city',text:'주변을 둘러보았지만 훈련장에는 아무도 없었다.\n그때 입구 쪽에서 급한 발소리가 들려왔다.'},
    {type:'city',speaker:'길드 직원',text:'여기 계셨군요.'},
    {type:'city',speaker:'주인공',text:'저를 찾으셨어요?'},
    {type:'city',speaker:'길드 직원',text:'길드장님께서 호출하셨습니다.\n가능한 한 빨리 길드로 와달라고 하셨습니다.'},
    {type:'city',speaker:'주인공',text:'길드장님이 저를요?'},
    {type:'city',speaker:'길드 직원',text:'자세한 내용은 직접 말씀해 주실 겁니다.'},
    {type:'city',text:'주인공은 조금 전 느꼈던 온기가 마음에 걸렸지만, 바닥에 떨어진 검을 주워 들었다.'},
    {type:'city',speaker:'주인공',text:'누구였는지는 모르겠지만...\n나중에 다시 만날 수 있겠지.'},
    {type:'city',text:'주인공은 길드 직원을 따라 훈련장을 나섰다.\n목적지는 길드장실이었다.'}
  ];
})();